dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
os:
  - linux
addons:
  apt:
    packages:
      - python-pygments
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run lint
  - npm run test:ci
  - git submodule init
  - git submodule update
  - cd docs && hugo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs/public
  target_branch: gh-pages
  on:
    branch: master